sudo: required
services:
  - docker

before_install:
  - docker build -t myfoxit/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true myfoxit/react-test npm test

after_success:
  - docker build -t myfoxit/multi-client ./client
  - docker build -t myfoxit/multi-nginx ./nginx
  - docker build -t myfoxit/multi-server ./server
  - docker build -t myfoxit/multi-worker ./worker
  # Login to docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  -  docker push myfoxit/multi-client
  -  docker push myfoxit/multi-nginx
  -  docker push myfoxit/multi-server
  -  docker push myfoxit/multi-worker


deploy:
  region: us-east-2
  edge: true
  provider: elasticbeanstalk
  app: multi-docker-app
  env: MultiDockerApp-env
  bucket_name: elasticbeanstalk-us-east-2-626389139069
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY 




